name: flutter_add_to_cart_button
description: A Flutter package to create Add to cart button. It will be useful for your awesome app.
version: 1.0.0
homepage: https://minhhung2556.github.io
repository: https://github.com/minhhung2556/romantic_project_flutter_add_to_cart_button

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter